version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 996256787865.dkr.ecr.us-east-2.amazonaws.com/admin-api
      - REPOSITORY_URI=996256787865.dkr.ecr.us-east-2.amazonaws.com/admin-api
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Admin/Admin.API/Dockerfile -t admin-api .
      - docker tag admin-api:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"admin-api","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

