version: 0.2
#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
    runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - echo Restore dependencies for Admin
      - dotnet restore Admin/Admin.API/Admin.API.csproj
  build:
    commands:
      - echo Build started
      - dotnet build Admin/Admin.API/Admin.API.csproj -c Release -o ./app/build
      - echo Publish started
      - dotnet publish Admin/Admin.API/Admin.API.csproj -c Release -o ./app/publish
  post_build:
    commands:
      - echo Postbuild
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  files:
    - Admin/Admin.API/app/publish/**/*
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths