version: 0.2

phases:
  pre_build:
    commands:
      - echo Restore dependencies for Admin
      - dotnet restore Admin/Admin.API/Admin.API.csproj
  build:
    commands:
      - echo Build started
      - dotnet build Admin/Admin.API/Admin.API.csproj -c Release -o ./app/build
      - echo Publish started
      - dotnet publish Admin/Admin.API/Admin.API.csproj -c Release -o ./app/publish
  post_build:
    commands:
      - echo Postbuild
  files:
    - Admin/Admin.API/app/publish/**/*
    - appspec.yml
    - installApp.sh
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths